var translationsAR = {
    'Home' : 'الرئيسية', 
    'Discover' : 'تعرف', 
    'Chat' : 'الدردشة', 
    'Likes' :'المفضلة', 
    'Views' :'الزائرون', 
    'Search' : 'البحث',
    'Meet New People':'دعنا نساعدك في ايجاد شريك حياتك بما يطابق مواصفاتك وهواياتك ' ,
    'Amazing Features':'مميزات رائعة',
    'Success Stories':'قصص النجاح',
    "Pal Match is the first platform of its kind to help you find your life partner":"منصة بال ماتش الأولى من نوعها لتساعدك في إيجاد شريك حياتك ",
    'Premium Membership':'اعضاء مميزين',
    'Latest Registered Members':'أحدث الأعضاء المسجلين', 
    'Find your life partner':"ابحث عن شريك حياتك",
    'START NOW FOR':"ابدا الان",
    "FREE":"مجانا",
    "DAY TRIAL":"ايام تجريبية",
    "Sign In":"تسجيل دخول",
    "Sign Up":"حساب جديد",
    "welcome":"مرحبا",
    "Notification":"الاشعارات",
    "Upgrade":"تحديث",
    "Profile":"الملف الشخصي",
    "Edit Profile":"تعديل البيانات الشخصية",
    "Change Password":"تعديل كلمة المرور",
    "LogOut":"تسجيل الخروج",
    "Get a membership":"احصل على عضوية",
    "Man":"رجل",
    "Men":"رجال",
    "Woman":"امراة",
    "Women":"نساء",
    "Men_count":"عدد الشباب ",
    "Women_count":"عدد الشابات ",
    "Age":"العمر",
    "country":"الدولة",
    "city":"المدينة",
    'Join Now':"انضم الان",
    "Read More":"قراءة المزيد",
    "Seeking a":"ابحث عن",
    "View Options":"عرض الخيارات",
    "Free 7 Days":" ايام مجانا 7",
    "Suggestions":"المقترحات ",
    "Search Suggestions":"اقتراحات البحث",
    "Advance Filter":"بحث متقدم",
    "Name":"الاسم",
    "Education":"التعليم ",
    "Search By":"البحث بواسطة ",
    "Total Members":"العدد الكلي",
    "Members Online":" المتاحين اون لاين الان",
    "Online":"متاحين حاليا",
    "The password and confirmed are not equal":"كلمة المرور وتاكيدها غير متطابقا",
    "Save":"حفظ",
    "Login":"دخول",
    "Email":"البريد الالكتروني",
    "Password":"كلمة المرور",
    "Remember Password":"تذكر كلمة المرور",
    "Forget Password":"نسيت كلمة المرور",
    "Or":"أو",
    "User Name":"اسم المستخدم",
    "Confirm password":"تأكيد كلمة المرور",
    "Terms & Conditions":"الاحكام والقيود",
    "Next":"التالي",
    "Years Old" : "سنوات",
    "Looking For":"ابحث عن",
    "Religion":"الديانة",
    "Hobbies":"المواهب",
    "For More Features":"لمزيد من الميزات",
    "Got It":"احصل عليها",
    "from":"من",
    "to":"الى",
    "Select":"اختر",
    "Like":"اضف الى المفضلة",
    "Dislike":"ازالة من المفضلة",
    "Delete":"حذف  المحادثة",
    "Resume":"السيرة الذاتية",
    "Gallery" :"الالبوم",
    "Information":"المعلومات الشخصية",
    "Gender" :"الجنس",
    "Social Links" :"روابط  مواقع التواصل الاجتماعي",
    "Determination":"حول",
    "Old Password":"كلمة المرور القديمة",
    "New Password":"كلمة المرور الجديدة",
    "Reset Password":"إعادة تعيين كلمة المرور",
    "Enter":"ادخل",
    "Reset":"إعادة التعيين",
    "Sent":"إرسال",
    "Forgot Your Password":"هل نسيت كلمة المرور ",
    "Enter the email associated with your account":"أدخل البريد الإلكتروني الخاص بحسابك",
    "You have Acount":"هل لديك حساب؟",
    "Login Please":"سجل دخول من فضلك",
    "With just a few clicks you will be ready to start your love adventure":"من خلال بضع نقرات فقط ، ستكون جاهزًا لبدء مغامرة الحب",
    "Birth Date":"تاريخ الميلاد",
    "Phone Number":"رقم الهاتف",
    "Male":"ذكر",
    "Female":"أنثى",
    "Enter your education here":"ادخل تخصصك",
    "Female":"أنثى",
    "More":"المزيد",
    "Profile Photo":"الصورة الشخصية",
    "Profile Cover":"صورة الغلاف",
    "Finish":"تسجيل",
    "My Profile":"الملف الشخصي",
    "Forgot Password":"نسيت كلمة المرور",
    "Reset Password":"تعديل كلمة المرور",
    "Edit Profile":"تعديل بياناتي",
    "year Old":"سنة",
    'error_activation' : 'عذراً، حسابك معطل من قبل الادارة.',
    'Tell us who you are!':"أخبرنا من انت!",
    'Find the right person':'ابحث عن الشخص المناسب',
    'Start Dating':"ابدأ بالمواعدة",
    'View More':"عرض المزيد",
    'Quick Search':"البحث السريع",
    'You May Like':"قد يعجبك",
    'Same Hobbies':"نفس المواهب",
    "Get to know":"بدأ يتعرف",
    'Recently Joined':"المنضمون حديثا",
    "Suitable For You":"المناسب لك",
    "you must accept terms and conditions":"يجب عليك قبول الشروط والأحكام",
    "Previous":"السابق",
    "suggests"  :"المقترحات"  ,
    "user_hobbies":"نفس المواهب",
    "user_Interests":"قد يعجبك",
    "new_registers":"المنضمون حديثا",
    "Change":"تغيير ",
    "Login Please":"سجل دخول من فضلك",
    "General Informations":"معلومات عامة",
    "Album":"الالبوم",
    "Date Of Birth":"تاريخ الميلاد",
    "Add Images":"اضافة صور",
    "Write Message ...":"اكتب رسالة ...",
    "Chats":"الدردشات",
    "Subscribe":"اشترك الان",
    "Save Successfully":"تم الحفظ بنجاح",
    "Maximum 400 letter" :"مسموح على الاكثر 400 حرف",
    "Add Photo":"إضافة صورة",
    "Visit Us On":"قم بزيارتنا على",
    "Contact Us":"اتصل بنا",
    "Privacy policy":"السياسة",
    "Terms and conditions":"الاحكام والشروط",
    "About Us":"نبذة عنا",
    "CMS":"CMS",
    "Help Center":"مركز المساعدة",
    "FAQS":"الأسئلة الشائعة",
    "Sign up to recieve a monthly email on the latest news!":"قم بالتسجيل لتلقي بريد إلكتروني شهري على آخر الأخبار!",
    "Enter your email address":"ادخل عنوان بريدك الالكتروني",
    "Account Name":"اسم الحساب",
    "You must select one at least":"يجب عليك اختيار واحد على الأقل",
    "The given data was invalid":"لم يتم تعبئة جميع البيانات المطلوبة",
    "Description":"الاستفسار",
    "Enter Your Name":"قم بادخال الاسم",
    "Enter Your Message":"قم بادخال ما تود الاستفسار عنه",
    "Enter Your Email":"قم بادخال الريد الالكتروني",
    "Send":"ارسال",
    "Copyright": "حقوق الطبع © 2020 جميعها محفوظة  لدى بال ماتش ",
    "year":"سنة",
    "month":"شهر",
    "your request is pending":"طلب المراسلة الخاص بك قيد الانتظار",
    "accept" : "قبول",
    "reject" : "رفض",
    "Some one liked you": "أعجب بك شخص ما",
    "Notifications":"الإشعارات",
    "like":"اعجاب",
    "Sent message for you by":"ارسل رسالة لك بواسطة ",
    'Skip':"تخطي",
    "Join":"انضم" ,
    "Who Are you":"كيف حالك؟",
    "Complete your online profile now with your passions":"أكمل ملفك الشخصي   الآن مع مواهبك",
    'So we can find people who like you for you':"حتى نتمكن من العثور على الأشخاص الذين يحبونك من أجلك",
    'Tell us about yourself':'أخبرنا عن نفسك',
    "to go to next":"للذهاب إلى التالي",
    "Drag or click to choose a cover photo":"اضغط لاضافة صورة الغلاف",
    "How Palmatch works" :'كيف تعمل Palmatch ',
    "Why Palmatch" :"لماذا منصة Palmatch "


}; 
