var translationsES = {

    'Home' : 'Home', 
    'Discover' : 'Discover', 
    'Chat' : 'Chat', 
    'Likes' :'Likes',
    'Views' :'Viewers', 
    'Search' : 'Search',
    'Meet New People':'Conocer gente nueva' ,
    'Amazing Features':'Características asombrosas',
    'Success Stories':'Historias de éxito',
    'Premium Membership':'Membresia premium',
    'Latest Registered Members':'Latest Registered Members',
    'Find your life partner':"Dinos quién eres Encuentra a tu compañero de vida",
    'START NOW FOR':"START NOW FOR",
    "FREE":"FREE",
    "DAY TRIAL":"DAY TRIAL",
    "Sign In":"Inicio de sesión",
    "Sign Up":"cuenta Nueva",
    "welcome":"welcome",
    "Notification":"Notification",
    "Upgrade":"Upgrade",
    "Profile":"Profile",
    "Edit Profile":"Edit Profile",
    "Change Password":"Change Password",
    "LogOut":"LogOut",
    "Get a membership":"Become A Member",
    "Man":"Hombre",
    "Men":"Men",
    "Woman":"Mujer",
    "Women":"Women",
    "Age":"Edad",
    'Join Now':"Únete ahora",
    "Read More":"Read More",
    "Seeking a":"Búsco",
    "View Options":"Ver opciones",
    "Free 7 Days":"Free 7 Days",
    "Suggestions":"Suggestions ",
    "Search Suggestions":"Search Suggestions",
    "Advance Filter":"Advance Filter",
    "Name":"Name",
    "Education":"Education ",
    "Search By":"Search By",
    "Total Members":"Total Members",
    "Members Online":"Disponible en linea",
    "Online":"Online",
    "The password and confirmed are not equal":"The password and confirmed are not equal",
    "You have Acount":"You have Acount?",
    "Save":"Save",
    "Login":"Login",
    "Email":"Email",
    "Password":"Password",
    "Remember Password":"Remember Password",
    "Forget Password":"Forget Password",
    "Or":"Or",
    "User Name":"User Name",
    "Confirm password":"Confirm password",
    "Terms & Conditions":"Terms & Conditions",
    "Next":"Next",
    "Years Old" : "Years Old",
    "Looking For":"Looking For",
    "Religion":"Religion",
    "Hobbies":"Passions",
    "For More Features":"For More Features",
    "Got It":"Got It",
    "from":"de",
    "to":"a",
    "Select":"Elegir",
    "Resume":"Resume",
    "Gallery" :"Gallery",
    "Information":"Information",
    "Gender" :"Gender",
    "Social Links" :"Social Links",
    "Determination":"Determination",
    "Old Password":"Old Password",
    "New Password":"New Password",
    "Reset Password":"Reset Password",
    "Enter":"Enter",
    "Reset":"Reset",
    "Sent":"Sent",
    "Forgot Your Password":"Forgot Your Password",
    "Enter the email associated with your account":"Enter the email associated with your account",
    "Login Please":"Login Please",
    "With just a few clicks you will be ready to start your love adventure":"With just a few clicks you will be ready to start your love adventure",
    "Birth Date":"Birth Date",
    "Phone Number":"Phone Number",
    "Male":"Male",
    "Enter your education here":"Enter your education here",
    "Female":"Female",
    "More":"More",
    "Profile Photo":"Profile Photo",
    "Profile Cover":"Profile Cover",
    "Finish":"Finish",
    "My Profile":"My Profile",
    "Forgot Password":"Forgot Password",
    "year Old":"year Old",
    'Tell us who you are!':"Dinos quién eres",
    'Find the right person':'Busca a la persona adecuada',
    'Start Dating':"Comienza a tener citas",
    'View More':"View More",
    'Quick Search':"Quick Search",
    'You May Like':"You May Like",
    'Same Hobbies':"Same Hobbies",
    "Get to know":"Get to know",
    'Recently Joined':"Recently Joined",
    "Suitable For You":"Suitable For You",
    "you must accept terms and conditions":"you must accept terms and conditions",
    "Previous":"Previous",
    "Change":"Change ",
    "Album":"Album",
    "country":"País",
    "city":"City",
    'error_activation' : 'Lo sentimos, su cuenta ha sido desactivada por el administrador.',
    "suggests"  :"Suggestions"  ,
    "user_hobbies":"Same Hobbies",
    "user_Interests":"You May Like",
    "new_registers":"Recently Joined",
    "General Informations":"General Information's",
    "Date Of Birth":"Date Of Birth",
    "Add Images":"Add Images",
    "Write Message ...":"Write Message ...",
    "Chats":"Chats",
    "Subscribe":"Subscribe",
    "Save Successfully":"Save Successfully",
    "Maximum 400 letter" :"Maximum 400 letter" ,
    "Add Photo":"Add Photo",
    "Like":"Like",
    "Delete":"Delete",
    "Dislike":"Dislike",
    "Visit Us On":"Visítenos en",
    "Contact Us":"Contacta con nosotras",
    "Privacy policy":"Política de privacidad",
    "Terms and conditions":"Términos y condiciones",
    "About Us":"Sobre nosotras",
    "CMS":"CMS",
    "Help Center":"Help Center",
    "FAQS":"FAQS",
    "Sign up to recieve a monthly email on the latest news!":'Regístrese para recibir un correo electrónico mensual con las últimas noticias!',
    "Enter your email address":"Ingrese su dirección de correo electrónico",
    "Account Name":"Account Name",
    "You must select one at least":"You must select one at least",
    "The given data was invalid":"The given data was invalid",
    "Description":"Description",
    "Enter Your Name":"Enter Your Name",
    "Enter Your Message":"Enter Your Message",
    "Enter Your Email":"Enter Your Email",
    "Send":"Send",
    "Copyright":"Copyright © 2020. Todos los derechos reservados por Palmatch",
    "year":"year",
    "month":"month",
    "your request is pending":"Your chat request is pending",
    "accept" : "Accept",
    "reject" : "Reject",
    "Some one liked you": "Some one liked you",
    "Sent message for you by":"Sent message for you by",
    "Notifications":"Notifications",
    "like":"Like",
    'Skip':"Skip",
    'So we can find people who like you for you':"So we can find people who like you for you",
    'Tell us about yourself':'Tell us about yourself',
    "to go to next":"to go to next",
    "Drag or click to choose a cover photo":"Drag or click to choose a cover photo",
    "Pal Match is the first platform of its kind to help you find your life partner":"Pal Match es la primera plataforma de este tipo para ayudarte a encontrar a tu compañero de vida",
    "Women_count":"número de mujeres jóvenes",
    "Men_count":"número de jóven",
    "Free":"Gratis",
    "How Palmatch works":"Cómo funciona Palmatch",
    "Why Palmatch":"Por qué Palmatch",

}; 

